apiVersion: v1
kind: Pod
metadata:
  name: mypod-week6
  labels:
    tier: frontend
spec:
  containers:
  - image: dhanujak/webapp-week6:1.1.1
    name: nodewebapp
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  